---
- name: Install Dependencies
 hosts: all
 tasks:
    - name: Update packages
      apt:
        upgrade: yes
        update_cache: yes

    - name: Install necessary software
      apt:
        - build-essential
        - cmake
        - git
        - libboost-all-dev
        - libssl-dev
        - libdb++-dev
        - libminiupnpc-dev
        - libevent-dev
        - autogen
        - automake
        - 1.14.2
        - libtool
        - make
        - g++
        - unzip
        - pkg-config
        - autoconf
        
- name: Clone Mining Software Repository
 hosts: all
 tasks:
    - name: Clone mining software
      git:
        repo: https://github.com/bitcoin/bitcoin.git
        dest: /opt/bitcoin
        version: 0.17.1

- name: Compile and Install Mining Software
 hosts: all
 tasks:
    - name: Compile and install
      command:
        cmd: |
          cd /opt/bitcoin
          ./autogen.sh
          ./configure --disable-wallet
          make
          make install

- name: Start Mining Bitcoin
 hosts: all
 tasks:
    - name: Start mining process
      command:
        cmd: |
          bitcoind -datadir=/opt/bitcoin -min -addr=bc1qs62yqlaqj40gd4u5yelyguag4ct74a0asne3xm
